### ISSUE TITLE
No data types are generated

### ISSUE THREAD

**Issue by jones1618** [jeffrose20/SQL_DDL_Generator#1]
Your script is useful but does not currently generate the data type part of DDLs.

Here's some code that will get the data types and sizes. When I get a chance I might turn this into a pull request but for now, here's the code snippet:

`DECLARE	@ObjectName SYSNAME

SET @ObjectName = 'client';

SELECT TOP 100
	sch.name AS [Schema],
	T.type_desc AS [Type],
	T.name AS [Table],
	-- T.type_desc,
    C.name AS [Column],
    P.name AS Data_Type ,
    P.max_length AS Size ,
    CAST(P.precision AS VARCHAR) + '/' + CAST(P.scale AS VARCHAR) AS Precision_Scale
FROM   sys.objects AS T
       JOIN sys.columns AS C ON T.object_id = C.object_id
       JOIN sys.types AS P ON C.system_type_id = P.system_type_id
	   JOIN sys.schemas sch ON sch.schema_id = T.schema_id
WHERE  (T.type_desc = 'USER_TABLE' OR T.type_desc = 'VIEW') AND P.name <> 'sysname'
  AND T.name LIKE '%'+@ObjectName+'%'  
ORDER BY T.name, C.name;`

**Comment by jeffrose20** [comment]
Thank you sir.  Could you check again?  Let me know your thoughts.

**Comment by jones1618** [comment]
Awesome. Looks good but I tried it on a few tables and found some gaps and necessary improvements. So, I submitted a Pull Request (my first ever on GitHub!) w/ improvements to support nvarchar, char and decimal types better. Let me know if that works for you.

**Comment by jeffrose20** [comment]
Looks great!
